name: Update Katas List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (optional)

jobs:
  update-katas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate README with solutions
        run: |
          echo "# Codewars Solutions" > README.md
          echo "## Solved Katas" >> README.md
          echo "" >> README.md
          for file in solutions/*.py; do
            echo "- [$(basename $file .py)](solutions/$(basename $file))" >> README.md
          done

      - name: Commit and push updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update kata solutions list" || echo "No changes to commit"
          git push
